# These are supported funding model platforms

github: [Gokujo]
ko_fi: devcraft
thanks_dev: gh/gokujo
buy_me_a_coffee: maharder
custom: ['https://paypal.me/MaximH', 'https://yoomoney.ru/to/41001454367103', 'https://dalink.to/maharder']
